import React ,{useEffect}from "react";

import "./header.css"
const Article = () => {

  return (
    <div className="flex flex-col items-center w-full">
  <h1 className="text-4xl font-bold text-content relative mb-16 mt-16 sm:text-center text-center">
  <span className="absolute inset-0 border-2 border-purple-700 rounded-lg animate-ping"></span>
  Explore Engaging Articles
</h1>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-48 mt-8 ">
        <div className="max-w-lg w-full bg-white shadow-md rounded-lg overflow-hidden mb-16 articles"  >
          <div className="p-4 flex flex-col justify-between  ">
            <h2 className="text-xl md:text-2xl font-semibold text-pink-700 mb-4">
              Harnessing Sentiment Analysis for Business Success
            </h2>
            <hr className="my-4 border-t-2 border-gray-300" />
            <p className="text-gray-600">
              Sentiment analysis or opinion mining is the computational study
              of people’s opinions, sentiments, attitudes, and emotions
              expressed in written language. It is one of the most active
              research areas in natural language processing and text mining
              in recent years. It has been applied in a variety of domains
              including business, market research, manufacturing, etc. This
              research was set down to discuss sentiment analysis including
              its types and classification, then moving on to describe how
              this analysis can benefit business; in terms of shedding the
              light in a case study that uses this analysis resulting in
              improving its work via customers. Keywords: sentiment analysis,
              opinion mining, natural language processing (NLP), machine
              learning.
            </p>
            <a
              href="https://1drv.ms/w/s!AsvQ27cQgFqWg4lU3rRtuEtBhjunuA"
              className="text-pink-700 hover:text-blue-700 block mt-4"
              target="_blank"
              rel="noopener noreferrer"
            >
              Read More
            </a>
          </div>
        </div>

        <div className="max-w-lg w-full bg-white shadow-md rounded-lg overflow-hidden mb-16 articles"  >
        <div className="p-4 flex flex-col justify-between">
            <h2 className="text-xl md:text-2xl font-semibold text-pink-700 mb-4">
              Addressing Common Challenges in Sentiment Analysis
            </h2>
            <hr className="my-4 border-t-2 border-gray-300" />
            <p className="text-gray-600">
              Recently, there are wide numbers of users that use the social
              network like Twitter, Facebook, Instagram to share various kinds
              of resources, express their opinions, thoughts, messages in real
              time. Thus, increase the amount of electronic content that
              generated by users. Sentiment analysis becomes a very interesting
              topic in research community. It is a natural language processing
              (NLP) technique used to determine whether data is positive,
              negative or neutral. It is one of the most active research areas
              in natural language processing and text mining in recent years.
              It has been applied in a variety of domains including business,
              market research, manufacturing, etc. This research was set down
              to discuss sentiment analysis including its benefits, tools,
              challenges and how does it work.
              <a
                href="https://1drv.ms/w/s!AsvQ27cQgFqWg4lWV5vB7AnGJc4G-g"
                className="text-pink-700 hover:text-blue-700 block mt-4"
                target="_blank"
                rel="noopener noreferrer"
              >
                Read More
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Article;
